declare class PacmanGame {
    private container;
    private canvas;
    private ctx;
    private qubic;
    private blocks;
    private gameEnded;
    private endMessage;
    private score;
    private isRunning;
    private animationFrameId;
    private lastTimestamp;
    private keyState;
    private xmrImage;
    private qubicImage;
    private xmrImageLoaded;
    private qubicImageLoaded;
    private currentEpoch;
    private blocksToNextEpoch;
    private blocksCollected;
    imagesLoaded: boolean;
    private onReadyCallback;
    constructor(container: HTMLDivElement);
    private checkImagesLoaded;
    onReady(callback: () => void): void;
    private resize;
    private generateBlocks;
    private handleKeyDown;
    private handleKeyUp;
    private handleTouchStart;
    private handleTouchMove;
    private handleTouchEnd;
    private updateQubicDirectionFromTouch;
    private update;
    render(): void;
    private gameLoop;
    private getBlocksForEpoch;
    private advanceEpoch;
    start(): void;
    pause(): void;
    initializeEpoch161(): void;
    restart(): void;
    destroy(): void;
}
export default PacmanGame;
